#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SwdEditor.Resource", IsApplication=true)]

namespace SwdEditor
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int cardBackgroundColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int cardCornerRadius = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cardElevation = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cardMaxElevation = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int cardPreventCornerOverlap = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int cardUseCompatPadding = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int contentPadding = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int contentPaddingBottom = 2130771978;
			
			// aapt resource value: 0x7f010007
			public const int contentPaddingLeft = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int contentPaddingRight = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int contentPaddingTop = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int cardview_dark_background = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int cardview_light_background = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int cardview_shadow_end_color = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int cardview_shadow_start_color = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int my_blue = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int my_gray = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int my_green = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int my_purple = 2130968582;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int cardview_compat_inset_shadow = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int cardview_default_elevation = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int cardview_default_radius = 2131034114;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int box = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080018
			public const int beginSeekBar = 2131230744;
			
			// aapt resource value: 0x7f080021
			public const int cardText = 2131230753;
			
			// aapt resource value: 0x7f08001f
			public const int cardView = 2131230751;
			
			// aapt resource value: 0x7f080004
			public const int editText1 = 2131230724;
			
			// aapt resource value: 0x7f080007
			public const int editText2 = 2131230727;
			
			// aapt resource value: 0x7f08000a
			public const int editText3 = 2131230730;
			
			// aapt resource value: 0x7f08000d
			public const int editText4 = 2131230733;
			
			// aapt resource value: 0x7f080010
			public const int editText5 = 2131230736;
			
			// aapt resource value: 0x7f080013
			public const int editText6 = 2131230739;
			
			// aapt resource value: 0x7f080016
			public const int editText7 = 2131230742;
			
			// aapt resource value: 0x7f080019
			public const int editText8 = 2131230745;
			
			// aapt resource value: 0x7f08001c
			public const int editText9 = 2131230748;
			
			// aapt resource value: 0x7f08001b
			public const int endSeekBar = 2131230747;
			
			// aapt resource value: 0x7f080020
			public const int imageButton1 = 2131230752;
			
			// aapt resource value: 0x7f08001e
			public const int linearLayout1 = 2131230750;
			
			// aapt resource value: 0x7f080022
			public const int openButton = 2131230754;
			
			// aapt resource value: 0x7f080000
			public const int sampleSeekBar = 2131230720;
			
			// aapt resource value: 0x7f080024
			public const int scrollTextView = 2131230756;
			
			// aapt resource value: 0x7f080023
			public const int scrollView1 = 2131230755;
			
			// aapt resource value: 0x7f08001d
			public const int statusText = 2131230749;
			
			// aapt resource value: 0x7f080001
			public const int tableLayout1 = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int tableRow1 = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int tableRow2 = 2131230725;
			
			// aapt resource value: 0x7f080008
			public const int tableRow3 = 2131230728;
			
			// aapt resource value: 0x7f08000b
			public const int tableRow4 = 2131230731;
			
			// aapt resource value: 0x7f080014
			public const int tableRow5 = 2131230740;
			
			// aapt resource value: 0x7f080011
			public const int tableRow6 = 2131230737;
			
			// aapt resource value: 0x7f08000e
			public const int tableRow7 = 2131230734;
			
			// aapt resource value: 0x7f080017
			public const int tableRow8 = 2131230743;
			
			// aapt resource value: 0x7f08001a
			public const int tableRow9 = 2131230746;
			
			// aapt resource value: 0x7f080003
			public const int textView1 = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int textView2 = 2131230726;
			
			// aapt resource value: 0x7f080009
			public const int textView3 = 2131230729;
			
			// aapt resource value: 0x7f08000c
			public const int textView4 = 2131230732;
			
			// aapt resource value: 0x7f08000f
			public const int textView5 = 2131230735;
			
			// aapt resource value: 0x7f080012
			public const int textView6 = 2131230738;
			
			// aapt resource value: 0x7f080015
			public const int textView7 = 2131230741;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CardView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Editor = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int ApplicationName = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Hello = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int CardView = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int CardView_Dark = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int CardView_Light = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int MyCustomTheme = 2131099651;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 0
			public const int CardView_cardBackgroundColor = 0;
			
			// aapt resource value: 1
			public const int CardView_cardCornerRadius = 1;
			
			// aapt resource value: 2
			public const int CardView_cardElevation = 2;
			
			// aapt resource value: 3
			public const int CardView_cardMaxElevation = 3;
			
			// aapt resource value: 5
			public const int CardView_cardPreventCornerOverlap = 5;
			
			// aapt resource value: 4
			public const int CardView_cardUseCompatPadding = 4;
			
			// aapt resource value: 6
			public const int CardView_contentPadding = 6;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingBottom = 10;
			
			// aapt resource value: 7
			public const int CardView_contentPaddingLeft = 7;
			
			// aapt resource value: 8
			public const int CardView_contentPaddingRight = 8;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingTop = 9;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
